#!/usr/bin/perl
$date=`date`;
$uid ="\<deneb-nx\@penguin\.it\>";
chomp($date);
open(FD,">>Changelog");
$string = "\n" . $date . " ". $uid;
print FD $string;
print $string;
print FD "\n";
print "\nList the changes (type end to quit):\n";
do
{
$value=<STDIN>;
chomp($value);
if  (!($value=~/end/i))
{
print FD "$value\n";
}
} while (!($value=~/end/i));
close(FD);
